### ISSUE TITLE
Stopped working on Firefox (until reinstall)

### ISSUE THREAD

**Issue by NicoWeio** [ActivityWatch/aw-watcher-web#105]
In the timeline and raw views, there was no browser activity from Firefox since the last day or so. The _aw-watcher-web_ extension said _Enabled_ and _Connected_, but the _Last sync_ was a while back. Restarting the browser did not help, neither did disabling and re-enabling.
What finally solved my problem was uninstalling and reinstalling the extension, after which I as prompted to agree to AW's data collection.
I suspect this happened because of the now-live consent update discussed in https://github.com/orgs/ActivityWatch/discussions/818, but haven't had time to dig deeper.

**Comment by eskoONE** [comment]
is it really working for you? because it did for me for a minute and then stopped recording again. im not sure whats causing this.

**Comment by NicoWeio** [comment]
@eskoONE Yes, it's still working as expected since the reinstall. Did you see the new data collection prompt upon reinstallation? What does your browser extension say when you click it (Enabled / Connected / Last Sync)?
Since you and @cachedout describe the same phenomenon, it might be worth pointing out that _I_ use _activitywatch-bin_ from the _AUR_ on _Manjaro Linux_ and since the extension's reinstall, I run _aw-server_ in a terminal (`$ aw-server --verbose`). You could try to do the same; maybe it tells you what the problem is.

**Comment by isle9** [comment]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.




- **OS name and version**: Ubuntu 22.10
- **ActivityWatch version**: v0.12.2

## Describe the bug
Seems like the background script doesn't start automatically when the browser is opened and only does so when I manually reneable it from the extension menu.

## To Reproduce
    1. Open the Firefox browser.
    2. Open the AW website.
    3. Check if the bucket is syncing.
    4. If not, disable and enable it again from the extension menu.
    5. Check again and it should work.

## Expected behavior
I expected it to automatically work without me needing to enable it every time.

## Documentation
Before manually re-enabling it:
![image](https://user-images.githubusercontent.com/74906541/230320916-82627a6a-f149-4a2b-9cb6-cb49efd247eb.png)
After:
![image](https://user-images.githubusercontent.com/74906541/230321084-fd59c8fc-cada-4a60-b5c8-246c3bc714ec.png)

**Comment by isle9** [comment]
Seems like the background script doesn't seem to start until you manually re-enable it every time you open the browser.

**Comment by ErikBjare** [comment]
Asked ChatGPT4 by feeding it the source file and @isle9's description:

![image](https://user-images.githubusercontent.com/1405370/230432078-5a14436b-4ac5-48f1-bbb1-cd227f9d3325.png)

Making a PR and new release now.

**Comment by ErikBjare** [comment]
Reopening until new version has been approved by Mozilla

**Comment by ErikBjare** [comment]
New version should be out now. Let me know if you find any issues!

**Comment by isle9** [comment]
Unfortunately, it seems like the Mozilla version still doesn't work properly. The background script still doesn't run automatically.

[This](https://github.com/ActivityWatch/aw-watcher-web/issues/93) issues seems like it might be connected too.

**Comment by ArgonBeryllium** [comment]
Bump, having this issue using the recently re-released `addons.mozilla.org` version.  
I've verified using the Query Explorer that there is indeed no data being received by the server beyond the last sync until restart(unchecking and re-checking the `Enabled` box), after which point logging seems to continue normally. The data in between is either lost or was never logged to begin with.

I'm running AW v0.12.2 (rust) and Firefox v111.0(64-bit) on Arch Linux.

**Comment by maestromac** [comment]
Similar to others, I have to uncheck-recheck "enabled" every time I launch my Firefox to get it working.

Firefox 102.0.1 Fedora 38

**Comment by isle9** [comment]
Any chance this gets fixed any time soon or should I just switch to Chromium?

**Comment by ErikBjare** [comment]
I released an updated version 6 days ago that should have fixed the bug: https://github.com/ActivityWatch/aw-watcher-web/issues/107#issuecomment-1558151995

If people can confirm it works, we can close this issue.
