### ISSUE TITLE
Add Arc Browser to browsers list

### ISSUE THREAD

**Issue by afonsocraposo** [ActivityWatch/aw-watcher-web#111]
Hey!
Can you add Arc Browser to the browsers list?
My issue is similar to https://github.com/ActivityWatch/aw-watcher-web/issues/61

<img width="1277" alt="image" src="https://github.com/ActivityWatch/aw-watcher-web/assets/30601767/35e7c1f0-997a-49e0-8786-3d845d20d1a7">

**Comment by noghartt** [comment]
+1, I'm using Arc browser as my main browser too, would love to have this browser filtered on the right tab

Sent a PR that maybe solve it: https://github.com/ActivityWatch/aw-webui/pull/473

**Comment by ragul-n** [comment]
I'm using the latest release with Arc. But it is still not working. Is there any quick fix for this?
