### ISSUE TITLE
Docker aw-server

### ISSUE THREAD

**Issue by accforgithubtest** [ActivityWatch/aw-watcher-web#116]
If I have a docker aw-server running, how can this extension send the data to server ?

Is there a way to specify the url to the aw-server to send data to ?

**Comment by ErikBjare** [comment]
Make the Docker bind to localhost:5600 and that should work.

If Docker is running remotely, you may need an SSH tunnel, see: https://docs.activitywatch.net/en/latest/remote-server.html
