### ISSUE TITLE
Running in two different chrome profiles confuses things?

### ISSUE THREAD

**Issue by paulirish** [ActivityWatch/aw-watcher-web#125]
I simultaneously use two different chrome profiles. one for work, one for non-work.

I want both to report into AW.

It seems like the backend is confused thinking they are trading off every ~minute but... in reality of course they're not.

You can kinda see this in the CSV export as the tabCount alternates back and forth (57 & 210):
![image](https://github.com/ActivityWatch/aw-watcher-web/assets/39191/7d32db2c-a26b-490c-8014-acb24839bd8a)

Can i fix this by manually separating the buckets somehow?  Thanks

**Comment by ErikBjare** [comment]
Yes this is unfortunately not well-supported. It has been requested before: https://github.com/ActivityWatch/aw-watcher-web/issues/82
