### ISSUE TITLE
Notification when connection successfully established after failure

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-web#13]
If you get a "Unable to connect" message you'll never get a "Now connected again" messag, you have to manually check if the last sync time in the popup is recent or now. This is bad UX, and would be easy to fix.

This was the "unable to connect" notification PR: https://github.com/ActivityWatch/aw-watcher-web/pull/10

**Comment by johan-bjareholt** [comment]
Fixed in #15 , closing
