### ISSUE TITLE
Chrome extension link broken

### ISSUE THREAD

**Issue by dgruano** [ActivityWatch/aw-watcher-web#136]
The Readme link to the chrome extension brings me to the homepage of the Chrome web store.
I don't know whether this is just me. Using Brave v1.69.168 on Ubuntu 22.04.

I suggest changing it to https://chromewebstore.google.com/detail/activitywatch-web-watcher/nglaklhklhcoonedhgnpgddginnjdadi. Will PR.

**Comment by dgruano** [comment]
Sorry, I just saw the open PR #135

**Comment by ErikBjare** [comment]
Thanks for the ping, just merged #135
