### ISSUE TITLE
Upload new version to Chrome Webstore

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-web#27]
As @johan-bjareholt reminded me today, we haven't updated the extension on Chrome Webstore as we have with the Firefox Extension. The last update to the Chrome extension was in 2017!

 - [x] Set up group publishing on the Chrome Webstore so @johan-bjareholt can also upload releases
 - [ ] Update the extension to the latest version

**Comment by ErikBjare** [comment]
I set up group publishing a while back, so @johan-bjareholt should be able to upload releases now.

**Comment by 8bitgentleman** [comment]
If the version of the Chrome Webstore is out of date how do we install the extension from source? Just downloading and dropping into the extensions page throws an error

<img width="503" alt="Screen Shot 2020-03-28 at 3 37 19 PM" src="https://user-images.githubusercontent.com/4028391/77832126-18ecb880-710a-11ea-94b3-c7802fdbc1d2.png">

**Comment by johan-bjareholt** [comment]
@8bitgentleman You need to build it first, see the Makefile.
The chrome webstore version shouldn't be outdated anymore by the way.

**Comment by 8bitgentleman** [comment]
@johan-bjareholt Are you sure? The firefox version was updated 8 months ago to 0.3.1 and the chrome version is at 0.2.3 updated in 2017

**Comment by johan-bjareholt** [comment]
@8bitgentleman Sorry, just saw that #42 was closed and assumed that this was already done but it was actually marked as a duplicated. Sloppy of me.

No they are not on different release schedules, the issue before was that only @ErikBjare had access to the webstore app so I couldn't upload a new version after I did significant changes. I have access now though, will try to update it to the newest version.

**Comment by johan-bjareholt** [comment]
The requirements for uploading to the Chrome Webstore are higher now, had to write the reason why each permission in the extension was needed.

At least it's done now, let's just hope that it gets approved.

**Comment by 8bitgentleman** [comment]
Looks like it's updated and working!

**Comment by johan-bjareholt** [comment]
Wow, that was quick!

Closing this issue then.
