### ISSUE TITLE
Add support for Webextension compatible browsers (Vivaldi, Brave, Opera)

### ISSUE THREAD

**Issue by mathieucaroff** [ActivityWatch/aw-watcher-web#29]
For some reason, trying to use aw-watcher-web on **Vivaldi** fails. No data is displayed in the browser tab. There's no aw-watcher-web-vivaldi displayed in the bucket selector. The same goes for **Opera**.

I can confirm the extension works in chrome and firefox, with the two buckets aw-watcher-web-chrome and aw-watcher-web-firefox visible.

Chromium pieces of data seem to be collected into the aw-watcher-web-chrome bucket.

**Comment by johan-bjareholt** [comment]
Vivaldi, Opera and Brave are the requests we've gotten asked about before.

What would be needed to get proper support would be 2 things:
- Make aw-watcher-web be able to get the browsers name so it's in it's own bucket ([which means to fix this TODO comment](https://github.com/ActivityWatch/aw-watcher-web/blob/4c3e075e56501330fb174ab174e185d4dcf60554/src/client.js#L35))
- Add the browsers appname to the web-ui query to filter it properly ([WIP PR is here, but worthless without fixing step 1 first](https://github.com/ActivityWatch/aw-webui/pull/131))

**Comment by kabili207** [comment]
If you want to detect Opera or Vivaldi via the user agent, looking for `OPR` and `Vivaldi` should be sufficient.

Brave on the other hand does not modify the standard Chrome user agent. [There is an open issue to address this](https://github.com/brave/brave-browser/issues/1052), but they apparently ran into issues with various sites.

Using something like [UAParser.js](https://github.com/faisalman/ua-parser-js) might be a great way to cover a wide variety of browsers.

**Comment by johan-bjareholt** [comment]
Thanks for the tip @kabili207, I have now done that change in a PR as it was very simple to implement.
