### ISSUE TITLE
Only "kind of" works with aw-server-rust

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-watcher-web#30]
The events are properly inserted in firefox and chrome and the CORS works properly but for some reason the watcher thinks that the server is unaccessible and shows "running" as false and gives notifications about not being connected.

Also need to investigate whether plugin ID in Origin change between versions or not.
Current Origins for the plugins are:
- `moz-extension://6b1794a0-5ae6-4443-aef9-7755717bb180`
- `chrome-extension://nglaklhklhcoonedhgnpgddginnjdadi`

**Comment by ErikBjare** [comment]
Plugin ID shouldn't change between production versions, but will most probably for development versions.

**Comment by johan-bjareholt** [comment]
@ErikBjare Good, in that case my more restrictive CORS setup in aw-server-rust is correct (force plugin-id on release builds while allowing any chrome/firefox extensions to fetch the data in testing)

**Comment by johan-bjareholt** [comment]
This is fixed, closing
