### ISSUE TITLE
Add an option to disable aw reporting and notification

### ISSUE THREAD

**Issue by tete1030** [ActivityWatch/aw-watcher-web#40]
ActivityWatch is really a great project and I love it. But the chrome extension has been too annoying on computer without AW installed. I'm using chrome on multiple computers and only one computer has AW installed. Chrome will sync installation and enabling/disabling of an extension across computers. 

So on computers without AW, I received many notifications telling me "Unable to send event to server". It appears so frequently, almost every 30 secs, that I have to disable the extension in chrome's extension manager. However, this will also disable the extension on my computer with AW. 

I hope there can be an option inside the extension for enabling/disabling its reporting and notification. Thank you.

**Comment by tete1030** [comment]
Hi, @johan-bjareholt . I want to say thank you for implementing this. I came here and found your PR by coincidence.

Last year, days after I filled this issue, I gave up AW for some reasons. Recently I decided to pick it up. Then I encountered this problem again. I forgot I had filled this issue so I came here to see if anyone has mentioned this problem. To my surprise it was from myself :P . Even more surprisingly, just hours ago you started that PR. Wow.

Anyway, appreciate your help!

**Comment by johan-bjareholt** [comment]
@tete1030 That's great to hear :-)

Hopefully I have enough spare time next week to complete the changes, we'll see!

**Comment by ErikBjare** [comment]
>I gave up AW for some reasons

@tete1030 Would you mind sharing the reasons? :)

**Comment by tete1030** [comment]
@johan-bjareholt Take your time. I now have AW installed on all computers. So this won't be a problem for now :XD

@ErikBjare Hi, glad you asked, though it was more of personal reasons, not about AW. It was my unrealistic expectation of it magically helping me on time management. It turned out, for myself, auditing time was not the way motivating me to change old habits. Recently I restarted using it only for recording and looking up my time history, no extra expectation.

**Comment by ErikBjare** [comment]
@tete1030 Thanks for the reply. You're right that AW won't magically help you with time management, and it's probably a common expectation when people start using time trackers of any kind. 

However, in the long run we hope to be able to build tools on top that could more directly help with time management, so we have an interest in feature requests in that spirit :)

**Comment by johan-bjareholt** [comment]
Uploaded the new version with the fix to Firefox and Chrome extension stores, should hopefully be updated soon!

**Comment by ErikBjare** [comment]
@johan-bjareholt I noticed the enable checkbox behaved a bit weird (enabled checkbox not showing as enabled) on first startup on my Android phone (where it can't connect to the server, not sure if that matters). Might be related to this line: 

https://github.com/ActivityWatch/aw-watcher-web/blob/4e7846c591bf7c604789467648e90e1e9cc7881c/static/popup.js#L5-L6

where `obj.enabled` could be `undefined` on first call if localStorage ins't yet set.

Also, the permission changes triggered a "this extension has changed their permissions, do you accept?" so the update isn't automatic.

**Comment by johan-bjareholt** [comment]
@ErikBjare Good point about the localStorage race, however I think you have to be incredibly fast on pressing the popup icon to actually see that?

> Also, the permission changes triggered a "this extension has changed their permissions, do you accept?" so the update isn't automatic.

Correct, that's on purpose though due to this issue which I fixed earlier.

https://github.com/ActivityWatch/aw-watcher-web/issues/47
