### ISSUE TITLE
User might get error notifications if aw-server starts after browser

### ISSUE THREAD

**Issue by je-l** [ActivityWatch/aw-watcher-web#41]
Some users might have system configured so that AW and browser both start automatically at startup. It should be expected that browser extension might start before the server.

Repro:
1. start browser with the extension enabled
2. start aw server

actual: user sees error message "Unable to send event to server"
expected: no error message is displayed

Perhaps it would make sense to poll the api until the server is available, and after that start the extension. If the api isn't available in x seconds, error message would be shown.

Would you accept a PR?

**Comment by ErikBjare** [comment]
The error messages are a bit greedy overall. The sensible thing would be to just wait for a few tries until we can be certain that the server is actually unavailable (and that it's not just in the process of starting, or if the system has just frozen for a few seconds).

I'd gladly accept a PR making such a change :)
