### ISSUE TITLE
Remote server

### ISSUE THREAD

**Issue by Skeyelab** [ActivityWatch/aw-watcher-web#44]
Is there a way to configure the IP address of a remote server for this watcher?

I changed the server setting in `aw-client.ini` file, but it seems the browser extension is still looking for a localhost server (unless I'm missing something).  A setting to set the IP of the server would be nice.

**Comment by ErikBjare** [comment]
You'll have to build it yourself and manually edit the IP, but the
recommended (and secure) way is to instead port forward using a SSH tunnel
(as has been discussed on the forum before).

We won't support editing the IP directly in the web extension for security
reasons, which you should clearly understand before you do such a thing.
