### ISSUE TITLE
Chrome Extension Redirects to incorrect server URL

### ISSUE THREAD

**Issue by 8bitgentleman** [ActivityWatch/aw-watcher-web#47]
Opening the Web UI from the chrome extension send you to a different URL than opening the dashboard from the actual Activity Watch menubar icon. 

Chrome extension sends you to: http://127.0.0.1:5600/#/
Activity Watch menubar icon sends you to: http://localhost:5600/#/

This is only an issue since activity watch settings are URL dependent.

**Comment by johan-bjareholt** [comment]
> This is only an issue since activity watch settings are URL dependent.

Oh, good point. That does indeed make things very confusing.

**Comment by johan-bjareholt** [comment]
Needed a fix in aw-watcher-js and now update aw-watcher-web to the newer version.

https://github.com/ActivityWatch/aw-client-js/pull/20

Thanks for reporting!
