### ISSUE TITLE
Add toggle for testing/not-testing

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-web#5]

**Comment by johan-bjareholt** [comment]
Description please? I thought this was working as it should?

**Comment by ErikBjare** [comment]
What? There is a testing toggle?

**Comment by ErikBjare** [comment]
There is a testing attribute in the client object, but what I want is a checkbox that can be clicked. Preferably the extension would start in testing mode when ran unpacked in developer mode.

**Comment by johan-bjareholt** [comment]
Ugh, sorry thought this was webui. Too many repos lol.

**Comment by ErikBjare** [comment]
Lol, I thought so too first when I read your reply.

**Comment by johan-bjareholt** [comment]
This would be very useful, currently in need of that

**Comment by ErikBjare** [comment]
Perhaps better than a toggle would be to autodetect if it's running as an
unpacked extension or as a stable, packaged, release?

**Comment by ErikBjare** [comment]
Seems like an easy fix: https://stackoverflow.com/a/12833511/965332

**Comment by ErikBjare** [comment]
I fixed this here: https://github.com/ActivityWatch/aw-watcher-web/pull/10
