### ISSUE TITLE
Add support for Microsoft Chromium Edge

### ISSUE THREAD

**Issue by LALAL4** [ActivityWatch/aw-watcher-web#53]
ActivityWatch Web Watcher not work in chromium edge

**Comment by johan-bjareholt** [comment]
It should be possible to install it today as it's a standard WebExtension.

If you give us the appname we can easily fix so it gets reported correctly in the web-ui (go to the raw data page in aw-watcher-window and find any event related to Chromium Edge and give us the exact text in the "appname" field).

**Comment by LALAL4** [comment]
the appname is msedge.exe

**Comment by ErikBjare** [comment]
@johan-bjareholt We've already fixed that: https://github.com/ActivityWatch/aw-webui/commit/d495f7f84996d0a5d9279bf335ec648a8062d622#diff-d32efe3611e62e63fc874a961dd5d5fa

@LALAL4 It should be available in the next version of ActivityWatch.

**Comment by LALAL4** [comment]
Thank you for your contribution to activitywatch.
im sorry for my poor English.
谢谢

**Comment by chaoky** [comment]
a few others names should be added for this to work on linux,
some of the variations I could install locally (with nixos, grabbed by window title):
Microsoft-edge
Microsoft-edge-stable
Microsoft-edge-beta

**Comment by maddykay-h** [comment]
... um... how do I install a watcher...?
