### ISSUE TITLE
Currently not compatible with STG

### ISSUE THREAD

**Issue by jtagcat** [ActivityWatch/aw-watcher-web#55]
So I have around 600 tabs, even though only a few of them are visible at a time.
[STG](https://github.com/drive4ik/simple-tab-groups) + aw-watcher-web = a lot of cpu usage, I would assume it's because STG does integrity checking, it might cycle through all 600 tabs.

**Comment by johan-bjareholt** [comment]
https://github.com/ActivityWatch/aw-watcher-web/blob/51a09bd/src/eventPage.js#L25

We only ask firefox/chrome for the active tab on the currently focused window and only do so when you switch tab and poll every 30 seconds, so if that's slow there's little we can do about it as we only ask for exactly what we want and nothing else.

If that case is too slow then this extension can't function, there is only one API for us to get this information and it's currently as optimized as possible. Maybe the firefox/chrome API can be optimized, but then you will have to fix it on their side.
