### ISSUE TITLE
Add tab.url to tab.tile

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/aw-watcher-web#59]
Since Activity Watch isn't currently categorizing with the url in mind (see [here](https://github.com/ActivityWatch/activitywatch/issues/352)), it might be a temorary solution to add the url to the title in this watcher. Maybe there could just be an option to turn this on, because this would really help in reducing uncategorized time.

**Comment by johan-bjareholt** [comment]
The webextension APIs only allow reading the titles, not writing/changing them so that's not possible unfortunately.

**Comment by watertrainer** [comment]
I meant the data which gets transferred to Activity Watch, sorry if this was unclear.
So instead of ``url`` and ``title`` in data at eventPage.js, just ``title`` gets transferred, but it consists of ``tab.url`` and ``tab.title``

**Comment by ErikBjare** [comment]
You seem to have misunderstood the issue. The issue is that the events reported by the web watcher aren't being used for classification on at all, only the AFK + window watcher events (which is where the title is coming from).

**Comment by watertrainer** [comment]
> You seem to have misunderstood the issue. The issue is that the events reported by the web watcher aren't being used for classification on at all, only the AFK + window watcher events (which is where the title is coming from). 

Ohhh okay, sorry for the misunderstanding
