### ISSUE TITLE
No changelog for extension releases

### ISSUE THREAD

**Issue by Victor239** [ActivityWatch/aw-watcher-web#66]
When pushing new extension updates please also create a new GitHub Release with associated changelog. There's currently nowhere to view the changelog for why the extension is being updated.

**Comment by johan-bjareholt** [comment]
The extension is rarely updated as it's quite minimal. The commit history is the best changelog.

But the firefox changelog is also available here https://addons.mozilla.org/en-US/firefox/addon/aw-watcher-web/versions/

**Comment by ErikBjare** [comment]
I consider this answered.

Closing.
