### ISSUE TITLE
Categorize open tabs based on Firefox Container's name

### ISSUE THREAD

**Issue by krillin666** [ActivityWatch/aw-watcher-web#69]
I  use Firefox Containers which tags the opened tabs with the name of the container, for example: Work, Shopping, Social Media, etc..

It would be a nice feature to be able to read the container's name and categorize it with the defined rules on ActivityWatch.

Thank you !

**Comment by ErikBjare** [comment]
The container name is exposed through any API available to the web extension. Therefore, this is impossible.
