### ISSUE TITLE
Firefox bucket not showing Top Browser Domains and Top Browser Url

### ISSUE THREAD

**Issue by Quiwy** [ActivityWatch/aw-watcher-web#87]
:white_check_mark: I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
:white_check_mark: I have searched the issues of this repo and believe that this is not a duplicate.

OS version and name: Ubuntu 20.04, Firefox 104.0a1 
ActivityWatch version: v0.11.0

# Describe the bug

There is no information on 'Top Browser Domains' and 'Top Browser Url' . It is just empty (see attached screenshot).
![image](https://user-images.githubusercontent.com/20048264/176613085-cef24cd5-70dd-4439-b501-9b216caa661a.png)

I am new to ActivityWatch. I am not sure whether logs are of any use in this case, but I can provide them if needed.

Raw data can be found in the specific tab:
![image](https://user-images.githubusercontent.com/20048264/176615348-5b987315-3f89-4d82-b8bd-4f7ca6561847.png)
![image](https://user-images.githubusercontent.com/20048264/176615455-75fd079a-3253-44e3-9061-b3687b23a041.png)

**Comment by Quiwy** [comment]
Yes window and afk watchers seems to work

![image](https://user-images.githubusercontent.com/20048264/176661140-c7ef086e-6aca-45bf-ae6d-0357b5c7d3a0.png)

**Comment by lincolnpires** [comment]
I'm having the same... but I'm using Firefox Dev ed. which changed name to `firefox-aurora`
Maybe this could be causing it for me, but IDRK: https://github.com/ActivityWatch/aw-webui/blob/47fed8be1077d729a8e52efdbcc486b382235fbc/src/queries.ts#L89

**Comment by Quiwy** [comment]
> I'm having the same... but I'm using Firefox Dev ed. which changed name to `firefox-aurora` Maybe this could be causing it for me, but IDRK: https://github.com/ActivityWatch/aw-webui/blob/47fed8be1077d729a8e52efdbcc486b382235fbc/src/queries.ts#L89

I guess that could be the problem as I'm using firefox dev too

**Comment by ErikBjare** [comment]
If you give us the correct appnames, or create a PR adding them to the
queries.js file mentioned above, we'd be happy to merge it :)

**Comment by Quiwy** [comment]
Sorry for the delay, I'm not sure on how to really know the name of the window, so you can find the output of 3 commands here

 ```
quiwy@ACER-14  ~/  xwininfo -root -children

xwininfo: Window id: 0x7c3 (the root window) (has no name)

  Root window id: 0x7c3 (the root window) (has no name)
  Parent window id: 0x0 (none)
     111 children:
     0x200017e "Firefox": ()  10x10+-100+-100  +-100+-100
     0x200013d "Firefox": ("firefox-trunk-nightly" "firefox-trunk-nightly")  200x200+0+0  +0+0
```
```
 quiwy@ACER-14  ~/  xlsclients
ACER-14  firefox-trunk-nightly

 quiwy@ACER-14  ~/   xwininfo
```
```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x200003e "12.10 - Find X-Window Name - Ask Ubuntu - askubuntu.com/ — Firefox Nightly"

  Absolute upper-left X:  1920
  Absolute upper-left Y:  0
  Relative upper-left X:  1920
  Relative upper-left Y:  0
  Width: 3440
  Height: 1440
  Depth: 32
  Visual: 0x7ac
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2000010 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1920+0  -0+0  -0-0  +1920-0
  -geometry 3440x1440-0+0
```

Let me know if you need anything else :smile:

**Comment by ErikBjare** [comment]
Thanks @Quiwy and @lincolnpires, I've added both in https://github.com/ActivityWatch/aw-webui/commit/130f00dbbe623fb86d1f60d9707f0865c16cf754, and it should work in the next release.

**Comment by SoutrikDas** [comment]
Hi , this is same thing is happening to me , I have both afk and window watchers active, but the visualisations cannot show anything. I also [commented](https://github.com/ActivityWatch/aw-webui/issues/357#issuecomment-2373295042) on this issue ( which I felt was the same ) 
Currently on v0.13.1
Browser : Brave
OS : MacOS 15

**Comment by Game4Move78** [comment]
@SoutrikDas Check if [this](https://github.com/ActivityWatch/aw-watcher-web/issues/148#issuecomment-2629126342) solves your problem.
