### ISSUE TITLE
mozilla add-on invalid

### ISSUE THREAD

**Issue by khonkhortisan** [ActivityWatch/aw-watcher-web#94]
https://addons.mozilla.org/en-US/firefox/addon/aw-watcher-web/
```
Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available [extensions](https://addons.mozilla.org/en-US/firefox/extensions/) or [themes](https://addons.mozilla.org/en-US/firefox/themes/), or by asking for help on our [community forums](https://discourse.mozilla.org/c/add-ons).
```

**Comment by ErikBjare** [comment]
I've answered this here: https://github.com/orgs/ActivityWatch/discussions/818

**Comment by ErikBjare** [comment]
I've now updated the [README](https://github.com/ActivityWatch/aw-watcher-web/blob/master/README.md) with workarounds. Thanks for reporting everyone!

**Comment by ErikBjare** [comment]
@kemege Looks like a non-standard make environment? 

Are you running from Powershell/cmd.exe? Try `git bash` or similar instead.

**Comment by kemege** [comment]
> @kemege Looks like a non-standard make environment?
> 
> Are you running from Powershell/cmd.exe? Try `git bash` or similar instead.

Thank you for your fast reply!
Yes, the error I reported are displayed with I use Powershell, but I also tried git bash yesterday, but it seemed to fail with a similar error (I did not remember the details).
I tried it again today, and it almost works, except that I had to invoke `browserify` and `make aw-watcher-web.zip` manually to get the ZIP file, as `npm run build` fails at `mkdir -p out; browserify src/*.js > out/app.js`, complaining that `The syntax of the command is incorrect.`.

**Comment by Pada0** [comment]
> I've now updated the [README](https://github.com/ActivityWatch/aw-watcher-web/blob/master/README.md) with workarounds. Thanks for reporting everyone!

Hi !
The command git pull --recurse-submodules https://github.com/ActivityWatch/aw-watcher-web.git or normal git pull doesn't work for me : no git respository.
Git clone works above works 

Hope it will be useful as AW is useful for me.

**Comment by replete** [comment]
> Hi ! The command git pull --recurse-submodules https://github.com/ActivityWatch/aw-watcher-web.git or normal git pull doesn't work for me : no git respository. Git clone works above works

You need to make a new local git repo with `git init` in a new local folder first.

[aw-watcher-web.zip](https://github.com/ActivityWatch/aw-watcher-web/files/10295231/aw-watcher-web.zip)

**Comment by Nanco300** [comment]
> > Hi ! The command git pull --recurse-submodules https://github.com/ActivityWatch/aw-watcher-web.git or normal git pull doesn't work for me : no git respository. Git clone works above works
> 
> You need to make a new local git repo with `git init` in a new local folder first.
> 
> [aw-watcher-web.zip](https://github.com/ActivityWatch/aw-watcher-web/files/10295231/aw-watcher-web.zip) - See, it built fine for me ;)

Here only install when I use "Load Temporary Addon"


![image](https://user-images.githubusercontent.com/34143366/210137692-7f2b3f17-0699-4f63-b3f1-48a294e43b97.png)

**Comment by Nanco300** [comment]
> 

Yes.

**Comment by Nanco300** [comment]
[{ef87d84c-2127-493f-b952-5b4e744245bc}.xpi.txt](https://github.com/ActivityWatch/aw-watcher-web/files/10327627/ef87d84c-2127-493f-b952-5b4e744245bc.xpi.txt)

Rename to .xpi

**Comment by KelvinJPS** [comment]
@Nanco300  I only can load in temporary extension, did you manage to install it normally ?

**Comment by NefariousFerris** [comment]
> For the time being you can just build the extension yourself. ~Installing unsigned extensions worked only in Firefox Nightly for me - regular Firefox Stable didn't work.~ Works for me in Firefox ESR as well.
> # Step 1 of 2 - downloading code and building the extension
> 
> Under Linux and MacOS, make sure you have the following commands available:
> 
>     * `npm` (appears after installing Node)
> 
>     * `make` (cmake)
> 
>     * `zip`
> 
> 
> then run:
> 
> ```shell
> $ git clone --recurse-submodules https://github.com/ActivityWatch/aw-watcher-web
> $ make
> ```
> 
> Verify that a `aw-watcher-web.zip` file appeared after running `make`. This is the extension as is - don't extract the `.zip` file.
> # Step 2 of 2 - installing the unsigned extension we just built
> 
>     1. In Firefox's URL bar, open `about:config` -> search `xpinstall.signatures.required` -> turn it off (set to false).
>        Turning off a security feature such as the one above may seem shady, but it's required because you just built the extension yourself - without signing it. Firefox won't allow you to install an unsigned extension otherwise.
> 
>     2. In Firefox's URL bar, open `about:addons` -> click cogwheel in top right -> click "Install add-on from file" -> select `aw-watcher-web/aw-watcher-web.zip`

so I have to do step 1 on Windows? tried on powershell and cmd prompt but wouldn't work. tried to upload the .zip to firefox after changing the setting in about:config but getting an error that the .zip is corrupt and firefox can't use it

**Comment by anthonyronda** [comment]
After reviewing [Mozilla's help docs](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) I can confirm that these steps did not work in the latest Firefox release, but did work in Firefox Developer Edition, even though the config toggle is available and changeable in both

**Comment by AlexanderMakarov** [comment]
Good job, [ErikBjare](https://github.com/ActivityWatch/aw-watcher-web/commits?author=ErikBjare)!

**Comment by AlexanderMakarov** [comment]
Good job, [Morpheus0x](https://github.com/ActivityWatch/aw-watcher-web/commits?author=Morpheus0x) and [ErikBjare](https://github.com/ActivityWatch/aw-watcher-web/commits?author=ErikBjare)!
