### ISSUE TITLE
Missing script: "compile"

### ISSUE THREAD

**Issue by VladChekunov** [ActivityWatch/aw-watcher-web#97]
Getting error while trying to run `make`:
```
npm ERR! Missing script: "compile"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
```

Node: v12.22.9
Npm: 8.5.1

**Comment by VladChekunov** [comment]
https://github.com/ActivityWatch/aw-watcher-web/issues/94#issuecomment-1315773537 ` --recurse-submodules` solved my issue. 
Please, add this information to README. It's very helpful.

**Comment by ErikBjare** [comment]
@VladChekunov I've now added proper build instructions to the README. Thanks for the feedback! :)
